routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

// User
Route::get("/signin", 'Main\LoginController@loginShow')->name('signinShow');
Route::post("/signin", 'Main\LoginController@signin')->name('signinPost');
Route::get("/signup", 'Main\LoginController@signupShow')->name('signupShow');
Route::post("/signup", 'Main\LoginController@signup')->name('signupPost');

Route::middleware("user_middle")->group(function() {
    Route::prefix("user")->name("user.")->group(function() {
        Route::get("/profile", "Main\ProfileController@index")->name("profile");
        Route::get("/seller-profile", "Main\ProfileController@sellerIndex")->name("seller_profile");
        Route::post('/importProducts', 'Main\ImportController@importing')->name("productsImporting");
        Route::post('/user-products/{id}', 'Main\ProductsController@userProducts')->name('userProducts');
        Route::get('/result', "Main\ProductsController@searchProduct")->name('search');
    });
});

// Admin
Route::get('admin/login', 'Admin\AuthController@login')->name('adminLogin');
Route::post('admin/signin', 'Admin\AuthController@signIn')->name('adminSignIn');
Route::get("admin/logout", "Admin\AuthController@logout")->name("logoutAdmin");

Route::middleware("admin_middle")->group(function() {
    Route::prefix("admin")->name('admin.')->group(function() {
        Route::resource("users", "Admin\UsersController", ['only' => ['index', 'create', 'update', 'destroy', 'store', 'show']]);//->except(['show', 'store', 'edit']);
        Route::resource("products", "Admin\ProductsController", ['only' => ['index', 'create', 'update', 'destroy', 'store', 'show']]);

        Route::post("users/getAll", "Admin\PagesController@getAllUsers")->name('allUsers');
        Route::post("products/getAll", "Admin\PagesController@getAllProducts")->name('allProducts');
    });
});


Auth::routes();

app/Http/Controllers/Main/ProfileController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    //
    public function index() {
        return view('site.profile.index');
    }

    public function sellerIndex() {
        return view('site.sellerProfile.index');
    }


}

resources/views/site/profile/index.blade.php
@extends('site.extentions.profile-layout')
@section('profile_index')
{{--{{ isset($failures) ? dd($failures) : "not variable" }}--}}
    <h1>Buyer</h1>
{{--    <a class="dropdown-item" href="{{ route('logout') }}"--}}
{{--       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">--}}
{{--        {{ __('Logout') }}--}}
{{--    </a>--}}
{{--    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
{{--        @csrf--}}
{{--    </form>--}}
    @if(Session::has("successUpload"))
        <b>{{ Session::get('successUpload')  }}</b>
    @endif
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p><b>Критерии</b><br>
                    <ul>
                        <li>цена</li>
                        <li>хорактеристики</li>
                        <li>Имя</li>
                        <li>описания</li>
                    </ul>
                </p>
                <form action="{{ route('user.search') }}" method="GET">
                    <div class="fomr-group">
                        <input type="text" placeholder="Поиск товаров" name="search" class="input-cotrol">
                        <button class="btn">Искать</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            @if(isset($details))
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Имя</th>
                        <th>хорактеристики</th>
                        <th>цена</th>
                        <th>описания</th>
                        <th>Единица Измерения</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($details as $user)
                        <tr>
                            <td>{{$user->product_title}}</td>
                            <td>{{$user->characteristics}}</td>
                            <td>{{$user->price_without_discount}}</td>
                            <td>{{$user->description}}</td>
                            <td>{{$user->unit_of_measure}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @endif
            @if(isset($message))
                <p>{{ $message }}</p>
            @endif
        </div>
    </div>


@endsection

@section('script')
    @php $user = \Illuminate\Support\Facades\Auth::user(); @endphp
    <script>
        $.ajax({
            url: '',
            type: 'get',
            cache: false,
            data: {},
            success: function(resp) {
                console.log("res");
            },
        }).fail(function(err, status, error){});
    </script>
@endsection