routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

// User
Route::get("/signin", 'Main\LoginController@loginShow')->name('signinShow');
Route::post("/signin", 'Main\LoginController@signin')->name('signinPost');
Route::get("/signup", 'Main\LoginController@signupShow')->name('signupShow');
Route::post("/signup", 'Main\LoginController@signup')->name('signupPost');

Route::middleware("user_middle")->group(function() {
    Route::prefix("user")->name("user.")->group(function() {
        Route::get("/profile", "Main\ProfileController@index")->name("profile");
        Route::get("/seller-profile", "Main\ProfileController@sellerIndex")->name("seller_profile");
        Route::post('/importProducts', 'Main\ImportController@importing')->name("productsImporting");
        Route::post('/user-products/{id}', 'Main\ProductsController@userProducts')->name('userProducts');
        Route::get('/result', "Main\ProductsController@searchProduct")->name('search');
    });
});

// Admin
Route::get('admin/login', 'Admin\AuthController@login')->name('adminLogin');
Route::post('admin/signin', 'Admin\AuthController@signIn')->name('adminSignIn');
Route::get("admin/logout", "Admin\AuthController@logout")->name("logoutAdmin");

Route::middleware("admin_middle")->group(function() {
    Route::prefix("admin")->name('admin.')->group(function() {
        Route::resource("users", "Admin\UsersController", ['only' => ['index', 'create', 'update', 'destroy', 'store', 'show']]);//->except(['show', 'store', 'edit']);
        Route::resource("products", "Admin\ProductsController", ['only' => ['index', 'create', 'update', 'destroy', 'store', 'show']]);

        Route::post("users/getAll", "Admin\PagesController@getAllUsers")->name('allUsers');
        Route::post("products/getAll", "Admin\PagesController@getAllProducts")->name('allProducts');
    });
});


Auth::routes();

resources/views/admin/includes/sidebar.blade.php
<div class="sidebar" data-color="purple">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
  -->
    <div class="logo">
        <a href="{{ route('home') }}" class="simple-text logo-mini">
{{--            Тендер--}}
        </a>
        <a href="{{ route('home') }}" class="simple-text logo-normal">
            Тендерплан
        </a>
    </div>
    <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
{{--            <li>--}}
{{--                <a href="./dashboard.html">--}}
{{--                    <i class="now-ui-icons design_app"></i>--}}
{{--                    <p>Dashboard</p>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            <li>--}}
{{--                <a href="./icons.html">--}}
{{--                    <i class="now-ui-icons education_atom"></i>--}}
{{--                    <p>Icons</p>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            <li>--}}
{{--                <a href="./map.html">--}}
{{--                    <i class="now-ui-icons location_map-big"></i>--}}
{{--                    <p>Maps</p>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            <li>--}}
{{--                <a href="./notifications.html">--}}
{{--                    <i class="now-ui-icons ui-1_bell-53"></i>--}}
{{--                    <p>Notifications</p>--}}
{{--                </a>--}}
{{--            </li>--}}
            <li class="active ">
                <a href="{{ route('admin.users.index') }}">
                    <i class="now-ui-icons users_single-02"></i>
                    <p>Users Config</p>
                </a>
            </li>
            <li class="active">
                <a href="{{ route('admin.products.index') }}">
                    <i class="now-ui-icons shopping_shop"></i>
                    <p>Products</p>
                </a>
            </li>
{{--            <li>--}}
{{--                <a href="./tables.html">--}}
{{--                    <i class="now-ui-icons design_bullet-list-67"></i>--}}
{{--                    <p>Table List</p>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            <li>--}}
{{--                <a href="./typography.html">--}}
{{--                    <i class="now-ui-icons text_caps-small"></i>--}}
{{--                    <p>Typography</p>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            --}}
        </ul>
    </div>
</div>